<?php

/**
 * @file
 * Module file for the portail_render_node_view module.
 * This solution should be redone with this in mind: https://www.computerminds.co.uk/articles/rendering-drupal-7-fields-right-way
 */

/**
 * Implements template_preprocess_field().
 */

function portail_render_node_view_preprocess_field(&$variables) {

  //Only change markup if the field is in the field_nom_production field collection.
  if($variables['element']['#field_name'] == 'field_nom_production') {
    
    //Go through each field in the field collection
    foreach($variables['items'] as $index => $entity) {

      $link_field = $entity['#options']['entity']->field_lien_production;

      //If the field is a term reference, and it has field_lien_production, get the title and URL
      if($entity['#options']['entity_type'] == "taxonomy_term" && array_key_exists('und',$link_field)) {
        $url = $link_field['und'][0]['url'];
        $title = $link_field['und'][0]['title'];
      
        $taxonomy_term_title = $entity['#title'];
        $taxonomy_term_url = $entity['#href'];

        //Only output markup for URL if one has been set.        
        $link_markup = '';

        if(isset($url)) {
          $link_markup = " [<a href='$url'>$title</a>]";
        }

        //Build markup for field.
        $markup = "<a href='$taxonomy_term_url'>$taxonomy_term_title</a>$link_markup";

        //Output the original field, plus the link associated with the term
        $variables['items'][$index] = array(
          '#markup' => $markup
        );
      }
    }
  }
}
