<?php

/**
 * @file
 * Module file for the portail_render_node_view module.
 */

/**
 * Implements template_preprocess_field().
 */

function portail_render_node_view_preprocess_field(&$variables) {
  print('<pre>');

  //Only change markup if the field is in the field_nom_production field collection.
  if($variables['element']['#field_name'] == 'field_nom_production') {
    
    //Go through each field in the field collection
    foreach($variables['items'] as $index => $entity) {

      $link_field = $entity['#options']['entity']->field_lien_production;

      //If the field is a term reference, and it has field_lien_production, get the title and URL
      if($entity['#options']['entity_type'] == "taxonomy_term" && isset($link_field)) {
        $url = $link_field['und'][0]['url'];
        $title = $link_field['und'][0]['title'];
      }

      //Output the original field, plus the link associated with the term
      $variables['items'][$index] = array(
        '#suffix' => "<a href='$url'>$title</a>" 
      );

    }

    //Get data associated with field, in this case with the Term Reference
    //$field_data = $variables['element']['#items'][0];
    
    //$url = $variables['element']['field_nom_production']['#options']['entity']->field_lien_production['und'][0]['url'];

    //$variables['items'][0] = array(
      //'#suffix' => 'hello'
    //);

    //Go through each element of the field to identify the field collection items
//    foreach(element_children($variables['element']) as $key) {
  //    $url = $variables['element'][$key]['#options']['entity']->field_lien_production['und'][0]['url'];
    //  $title = $variables['element'][$key]['#options']['entity']->field_lien_production['und'][0]['title'];
      //var_dump($variables['element'][$key]);
//Get each field collection item
      //$field_collections = array_pop($variables['element'][$key]['entity']['field_collection_item']);
   // }

    //var_dump();

    //var_dump($variables['element']['#object']);
  }
  print('</pre>');
}
